[project]
name = "test-hft"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "torch>=2.0.0",
    "transformers>=4.30.0",
    "pymupdf>=1.23.0",
    "pillow>=10.0.0",
    "reportlab>=4.0.0",
]
